services:
  - type: web
    name: auth-backend
    env: node
    buildCommand: npm install
    startCommand: node src/server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_FROM_EMAIL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ADMIN_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
